### ISSUE TITLE
Setup hook for packagist !

### ISSUE THREAD

**Issue by julienbourdeau** [PrestaShop/TranslationToolsBundle#14]
If we dont, it's only updated once a week.

Ask @maximebiloe he's the official PrestaShop expert !

**Comment by maximebiloe** [comment]
It's already done. @mickaelandrieu asked me to do it last week. He was faster than you! 😛

**Comment by mickaelandrieu** [comment]
:sunglasses:

**Comment by julienbourdeau** [comment]
💯
