### ISSUE TITLE
Make this package compatible with Twig 3.x

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/TranslationToolsBundle#70]
Currently, this project requires `twig/twig` package of version < 3 in the `composer.json` file.

Important to be able to use this package in projects that use Twig 3.x.

**Comment by matks** [comment]
Could be nice to have ... provided it does not require drop of twig 1 or 2 😅

**Comment by mvorisek** [comment]
Based on https://symfony.com/blog/preparing-your-applications-for-twig-3 is should be possible, the major BC break is that all non-namespaced class names are no longer supported. But 1 and 2 versions should provide the namespaced classes, so BC should be possible.
